import type {
  MetricInteractionDefinition,
  SystemKey,
} from '../types'

const keysBySystem = {
  sca: [
    'project_count',
    'component_total',
    'vulnerability_total',
    'criticalRisks',
    'high',
    'medium',
    'low',
    'vulnerableComponents',
    'healthyRate',
    'blocked_count',
    'assets',
    'devops',
  ],
  'train-exam': [
    'course_total',
    'question_total',
    'question_published_total',
    'question_draft_total',
    'paper_total',
    'paper_published_total',
    'exam_total',
    'final_result_total',
    'final_passed_total',
    'pass_rate',
    'activeCourses',
    'learners',
    'completionRate',
    'certificates',
  ],
  reminder: [
    'expiring',
    'todayDue',
    'totalReminders',
    'successRate',
    'total',
    'success',
    'channelBreakdown_sms_total',
    'expiring7d',
    'expiring30d',
    'riskAmount',
    'deliveryRate',
    'day7',
    'day30',
    'day60',
    'day90',
    'customer_count',
    'license_count',
  ],
} as const satisfies Record<SystemKey, readonly string[]>

type InteractionKey = (typeof keysBySystem)[SystemKey][number]

const groupByKey = {
  project_count: 'asset',
  component_total: 'asset',
  assets: 'asset',
  vulnerability_total: 'risk',
  criticalRisks: 'risk',
  high: 'risk',
  medium: 'risk',
  low: 'risk',
  vulnerableComponents: 'risk',
  healthyRate: 'governance',
  blocked_count: 'governance',
  devops: 'governance',
  course_total: 'content',
  question_total: 'content',
  question_published_total: 'content',
  question_draft_total: 'content',
  paper_total: 'content',
  paper_published_total: 'content',
  exam_total: 'exam',
  final_result_total: 'exam',
  final_passed_total: 'exam',
  pass_rate: 'outcome',
  activeCourses: 'content',
  learners: 'learner',
  completionRate: 'outcome',
  certificates: 'outcome',
  expiring: 'expiry',
  todayDue: 'expiry',
  expiring7d: 'expiry',
  expiring30d: 'expiry',
  day7: 'expiry',
  day30: 'expiry',
  day60: 'expiry',
  day90: 'expiry',
  riskAmount: 'expiry',
  totalReminders: 'delivery',
  successRate: 'delivery',
  total: 'delivery',
  success: 'delivery',
  channelBreakdown_sms_total: 'delivery',
  deliveryRate: 'delivery',
  customer_count: 'customer',
  license_count: 'customer',
} satisfies Record<InteractionKey, string>

const labelByKey = {
  project_count: '项目数量',
  component_total: '组件总数',
  vulnerability_total: '漏洞总数',
  criticalRisks: '严重风险',
  high: '高危',
  medium: '中危',
  low: '低危',
  vulnerableComponents: '风险组件',
  healthyRate: '健康率',
  blocked_count: '阻断任务',
  assets: '资产',
  devops: '研发运维',
  course_total: '课程总数',
  question_total: '题目总数',
  question_published_total: '已发布题目',
  question_draft_total: '草稿题目',
  paper_total: '试卷总数',
  paper_published_total: '已发布试卷',
  exam_total: '考试总数',
  final_result_total: '最终成绩数',
  final_passed_total: '最终通过数',
  pass_rate: '通过率',
  activeCourses: '进行中课程',
  learners: '参训人数',
  completionRate: '完成率',
  certificates: '证书签发',
  expiring: '到期授权',
  todayDue: '今日到期',
  totalReminders: '提醒总数',
  successRate: '触达成功率',
  total: '总数',
  success: '成功触达',
  channelBreakdown_sms_total: '短信提醒总数',
  expiring7d: '7 天到期',
  expiring30d: '30 天到期',
  riskAmount: '风险金额',
  deliveryRate: '提醒触达率',
  day7: '7 天内到期',
  day30: '30 天内到期',
  day60: '60 天内到期',
  day90: '90 天内到期',
  customer_count: '客户数量',
  license_count: '授权数量',
} satisfies Record<InteractionKey, string>

export const createMetricInteractions = (
  systemKey: SystemKey,
): MetricInteractionDefinition[] => {
  const keys: readonly InteractionKey[] = keysBySystem[systemKey]
  return keys.map((key) => {
    const group = groupByKey[key]
    const label = labelByKey[key]
    return {
      key,
      label,
      group,
      relatedKeys: keys.filter(
        (candidate) => candidate !== key && groupByKey[candidate] === group,
      ),
      detailPath: '/',
      description: `${label}用于展示当前模板中的业务状态和变化情况。`,
    }
  })
}
