#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "${SCRIPT_DIR}/../.." && pwd)
OUT_FILE="${1:-${ROOT_DIR}/.env.images}"

trim_trailing_slash() {
  local value="$1"
  while [ -n "$value" ] && [ "${value%/}" != "$value" ]; do
    value="${value%/}"
  done
  printf '%s' "$value"
}

is_placeholder() {
  local value="${1:-}"
  case "$value" in
    ''|change_me_*|replace-with-*|dev-secret-change-me)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

probe_image() {
  local image="$1"
  if [ -z "$image" ]; then
    return 1
  fi
  docker manifest inspect "$image" >/dev/null 2>&1
}

resolve_image() {
  local alias_name="$1"
  local official_image="$2"
  shift 2
  local explicit="${!alias_name:-}"
  if ! is_placeholder "$explicit"; then
    printf '%s' "$explicit"
    return 0
  fi

  local candidate
  for candidate in "$@"; do
    [ -n "$candidate" ] || continue
    if probe_image "$candidate"; then
      printf '%s' "$candidate"
      return 0
    fi
  done

  printf '%s' "$official_image"
}

build_library_candidate() {
  local prefix
  prefix=$(trim_trailing_slash "${ALIYUN_DOCKERHUB_PREFIX:-}")
  local image_path="$1"
  if [ -z "$prefix" ]; then
    return 0
  fi
  printf '%s/%s' "$prefix" "$image_path"
}

build_daocloud_candidate() {
  local prefix
  prefix=$(trim_trailing_slash "${DAOCLOUD_DOCKERHUB_PREFIX:-docker.m.daocloud.io/library}")
  local image_path="$1"
  if [ -z "$prefix" ]; then
    return 0
  fi
  printf '%s/%s' "$prefix" "$image_path"
}

build_vendor_candidate() {
  local prefix_var="$1"
  local image_path="$2"
  local prefix
  prefix=$(trim_trailing_slash "${!prefix_var:-}")
  if [ -z "$prefix" ]; then
    return 0
  fi
  printf '%s/%s' "$prefix" "$image_path"
}

write_alias() {
  local alias_name="$1"
  local official_image="$2"
  shift 2
  local resolved
  resolved=$(resolve_image "$alias_name" "$official_image" "$@")
  printf '%s=%s\n' "$alias_name" "$resolved" >> "$OUT_FILE"
}

main() {
  mkdir -p "$(dirname "$OUT_FILE")"
  : > "$OUT_FILE"
  {
    echo "# Generated by scripts/deploy/resolve-image-sources.sh"
    echo "# Aliyun candidate images are preferred only when they can be probed successfully."
  } >> "$OUT_FILE"

  write_alias NODE_20_BOOKWORM_IMAGE node:20-bookworm \
    "$(build_daocloud_candidate node:20-bookworm)" \
    "$(build_library_candidate node:20-bookworm)"
  write_alias NODE_20_BOOKWORM_SLIM_IMAGE node:20-bookworm-slim \
    "$(build_daocloud_candidate node:20-bookworm-slim)" \
    "$(build_library_candidate node:20-bookworm-slim)"
  write_alias NODE_20_ALPINE_IMAGE node:20-alpine \
    "$(build_library_candidate node:20-alpine)"
  write_alias NGINX_ALPINE_IMAGE nginx:alpine \
    "$(build_library_candidate nginx:alpine)"
  write_alias MYSQL_IMAGE mysql:8.0 \
    "$(build_library_candidate mysql:8.0)"
  write_alias GOLANG_1_22_ALPINE_IMAGE golang:1.22-alpine \
    "$(build_library_candidate golang:1.22-alpine)"
  write_alias ALPINE_3_20_IMAGE alpine:3.20 \
    "$(build_library_candidate alpine:3.20)"
  write_alias ONLYOFFICE_DOCUMENTSERVER_IMAGE onlyoffice/documentserver:latest \
    "$(build_vendor_candidate ALIYUN_ONLYOFFICE_PREFIX onlyoffice/documentserver:latest)"
  write_alias CP_ZOOKEEPER_IMAGE confluentinc/cp-zookeeper:7.8.7 \
    "$(build_vendor_candidate ALIYUN_CONFLUENTINC_PREFIX confluentinc/cp-zookeeper:7.8.7)"
  write_alias CP_KAFKA_IMAGE confluentinc/cp-kafka:7.8.7 \
    "$(build_vendor_candidate ALIYUN_CONFLUENTINC_PREFIX confluentinc/cp-kafka:7.8.7)"
  write_alias KAFKA_UI_IMAGE provectuslabs/kafka-ui:latest \
    "$(build_vendor_candidate ALIYUN_PROVECTUSLABS_PREFIX provectuslabs/kafka-ui:latest)"
}

main "$@"
