from __future__ import annotations

from .base import DocumentTemplate, GenericDocumentTemplate
from .templates import (
    ACCEPTANCE_REPORT_TEMPLATE,
    INCIDENT_REPORT_TEMPLATE,
    MEETING_MINUTES_TEMPLATE,
    POLICY_INTERPRETATION_TEMPLATE,
    PROJECT_REPORT_TEMPLATE,
    RISK_ASSESSMENT_TEMPLATE,
    SOP_TEMPLATE,
    TOOL_UPDATE_RECORD_TEMPLATE,
    WEEKLY_REPORT_TEMPLATE,
    WORK_PLAN_TEMPLATE,
)


GENERIC_TEMPLATE = GenericDocumentTemplate()
DOCUMENT_TEMPLATES = {
    GENERIC_TEMPLATE.code: GENERIC_TEMPLATE,
    WORK_PLAN_TEMPLATE.code: WORK_PLAN_TEMPLATE,
    MEETING_MINUTES_TEMPLATE.code: MEETING_MINUTES_TEMPLATE,
    PROJECT_REPORT_TEMPLATE.code: PROJECT_REPORT_TEMPLATE,
    INCIDENT_REPORT_TEMPLATE.code: INCIDENT_REPORT_TEMPLATE,
    RISK_ASSESSMENT_TEMPLATE.code: RISK_ASSESSMENT_TEMPLATE,
    ACCEPTANCE_REPORT_TEMPLATE.code: ACCEPTANCE_REPORT_TEMPLATE,
    WEEKLY_REPORT_TEMPLATE.code: WEEKLY_REPORT_TEMPLATE,
    SOP_TEMPLATE.code: SOP_TEMPLATE,
    TOOL_UPDATE_RECORD_TEMPLATE.code: TOOL_UPDATE_RECORD_TEMPLATE,
    POLICY_INTERPRETATION_TEMPLATE.code: POLICY_INTERPRETATION_TEMPLATE,
}


def get_document_template(template_code: str | None) -> DocumentTemplate:
    return DOCUMENT_TEMPLATES.get(template_code or "", GENERIC_TEMPLATE)


def list_document_templates() -> list[dict[str, str]]:
    return [
        {"code": t.code, "name": t.name}
        for t in DOCUMENT_TEMPLATES.values()
    ]
