"""foundation

Revision ID: 0001_foundation
Revises:
Create Date: 2026-06-19 09:26:09.504739
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_foundation'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assistants',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('ai_assistants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_assistants_status'), ['status'], unique=False)

    op.create_table('ai_tasks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('assistant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('safety_notice', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['ai_assistants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('ai_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tasks_assistant_id'), ['assistant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tasks_status'), ['status'], unique=False)

    op.create_table('ai_generation_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('sso_user_id', sa.String(length=64), nullable=False),
    sa.Column('username_snapshot', sa.String(length=128), nullable=False),
    sa.Column('department_snapshot', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('prompt_external_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('input_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('output_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('input_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('output_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.String(length=32), nullable=False),
    sa.Column('completion_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('model_display_name', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('usage_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ai_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('ai_generation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generation_records_sso_user_id'), ['sso_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generation_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generation_records_task_id'), ['task_id'], unique=False)

    op.create_table('ai_task_fields',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('field_key', sa.String(length=96), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.String(length=512), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('validation_json', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ai_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'field_key'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('ai_task_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_task_fields_task_id'), ['task_id'], unique=False)

    op.create_table('ai_task_prompt_bindings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('prompt_external_id', sa.BigInteger(), nullable=False),
    sa.Column('version_policy', sa.String(length=16), nullable=False),
    sa.Column('pinned_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ai_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('ai_task_prompt_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_task_prompt_bindings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('ai_task_prompt_bindings')
    op.drop_table('ai_task_fields')
    op.drop_table('ai_generation_records')
    op.drop_table('ai_tasks')
    op.drop_table('ai_assistants')
