FROM docker.m.daocloud.io/library/node:20-bookworm AS build

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . ./
RUN npm run build

FROM docker.m.daocloud.io/library/nginx:1.25-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
